name: Cypress Tests

on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Cache Cypress
        uses: actions/cache@v2
        with:
          path: ~/.cache/Cypress
          key: ${{ runner.os }}-cypress-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-cypress-

      # Usar Cypress GitHub Action para simplificar la configuración
      - name: Cypress.io
        uses: cypress-io/github-action@v6.5.0
        with:
          browser: chrome # Puedes especificar el navegador
          start: npm start # Comando para iniciar tu servidor
          wait-on: http://localhost:3000 # URL a esperar antes de correr las pruebas
          config-file: cypress.config.js # Asegúrate que el nombre del archivo de configuración sea correcto

      - name: Send Email Notification
        if: failure()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          to: karielcode@gmail.com
          subject: "Cypress Test Results"
          body: "The Cypress tests have failed. Check the details in the GitHub Actions log here 'https://github.com/ErosCalvimonti/challenge-qa'."
          from: ${{ secrets.SMTP_USERNAME }}
