name: Cypress Tests

on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cypress-io/github-action@v2
        with:
          build: npm run build
          start: npm start
          wait-on: "http://localhost:3000"
          config-file: cypress.config.js
      - name: Send Email Notification
        if: failure()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          to: karielcode@gmail.com
          subject: "Cypress Test Results"
          body: "The Cypress tests have failed. Check the details in the GitHub Actions log."
          from: ${{ secrets.SMTP_USERNAME }}
